GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6144348aeaa43adbb5349b79

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/personsapi/persons/4

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Liisas Marttinen",
    "number": "040-11"
}

###

PUT http://localhost:3001/api/persons/614579def3d70a6d43f09049 HTTP/1.1
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-24323221"
}