GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/api/persons/6144348aeaa43adbb5349b79

###

GET http://localhost:3001/api/persons/info

###

DELETE http://localhost:3001/api/personsapi/persons/4

###

POSThttp://localhost:3001/api/persons/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-243563"
}